//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace AVDClient.WebStore {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebStoreSoapBinding", Namespace="http://www.webstore.org")]
    public partial class WebStore : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDatabaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AktSverkyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AVDClientRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAVDClientVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAVDClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback AVDClientRegistrationIPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebStore() {
            this.Url = global::AVDClient.Properties.Settings.Default.WindowsFormsApplication1_WebStore_WebStore;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event FormOrderCompletedEventHandler FormOrderCompleted;
        
        /// <remarks/>
        public event UpdateDatabaseCompletedEventHandler UpdateDatabaseCompleted;
        
        /// <remarks/>
        public event GetInvoiceListCompletedEventHandler GetInvoiceListCompleted;
        
        /// <remarks/>
        public event AktSverkyCompletedEventHandler AktSverkyCompleted;
        
        /// <remarks/>
        public event GetImageCompletedEventHandler GetImageCompleted;
        
        /// <remarks/>
        public event GetNewsListCompletedEventHandler GetNewsListCompleted;
        
        /// <remarks/>
        public event GetCustomerInfoCompletedEventHandler GetCustomerInfoCompleted;
        
        /// <remarks/>
        public event AVDClientRegistrationCompletedEventHandler AVDClientRegistrationCompleted;
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event GetAVDClientVersionCompletedEventHandler GetAVDClientVersionCompleted;
        
        /// <remarks/>
        public event UpdateAVDClientCompletedEventHandler UpdateAVDClientCompleted;
        
        /// <remarks/>
        public event AVDClientRegistrationIPCompletedEventHandler AVDClientRegistrationIPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:Test", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:FormOrder", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string FormOrder(Customers Customer, Order Order) {
            object[] results = this.Invoke("FormOrder", new object[] {
                        Customer,
                        Order});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormOrderAsync(Customers Customer, Order Order) {
            this.FormOrderAsync(Customer, Order, null);
        }
        
        /// <remarks/>
        public void FormOrderAsync(Customers Customer, Order Order, object userState) {
            if ((this.FormOrderOperationCompleted == null)) {
                this.FormOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormOrderOperationCompleted);
            }
            this.InvokeAsync("FormOrder", new object[] {
                        Customer,
                        Order}, this.FormOrderOperationCompleted, userState);
        }
        
        private void OnFormOrderOperationCompleted(object arg) {
            if ((this.FormOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormOrderCompleted(this, new FormOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:UpdateDatabase", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string UpdateDatabase(Customers Customer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] out byte[] Data) {
            object[] results = this.Invoke("UpdateDatabase", new object[] {
                        Customer});
            Data = ((byte[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDatabaseAsync(Customers Customer) {
            this.UpdateDatabaseAsync(Customer, null);
        }
        
        /// <remarks/>
        public void UpdateDatabaseAsync(Customers Customer, object userState) {
            if ((this.UpdateDatabaseOperationCompleted == null)) {
                this.UpdateDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDatabaseOperationCompleted);
            }
            this.InvokeAsync("UpdateDatabase", new object[] {
                        Customer}, this.UpdateDatabaseOperationCompleted, userState);
        }
        
        private void OnUpdateDatabaseOperationCompleted(object arg) {
            if ((this.UpdateDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDatabaseCompleted(this, new UpdateDatabaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:GetInvoiceList", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string GetInvoiceList(Customers Customer, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Date, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] out Invoice[] InvoiceList) {
            object[] results = this.Invoke("GetInvoiceList", new object[] {
                        Customer,
                        Date});
            InvoiceList = ((Invoice[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceListAsync(Customers Customer, System.DateTime Date) {
            this.GetInvoiceListAsync(Customer, Date, null);
        }
        
        /// <remarks/>
        public void GetInvoiceListAsync(Customers Customer, System.DateTime Date, object userState) {
            if ((this.GetInvoiceListOperationCompleted == null)) {
                this.GetInvoiceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceListOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceList", new object[] {
                        Customer,
                        Date}, this.GetInvoiceListOperationCompleted, userState);
        }
        
        private void OnGetInvoiceListOperationCompleted(object arg) {
            if ((this.GetInvoiceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceListCompleted(this, new GetInvoiceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:AktSverky", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string AktSverky(Customers Customer, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Date1, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Date2, [System.Xml.Serialization.XmlArrayAttribute("AktSverky", IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("AktSverkyRows", IsNullable=false)] out AktSverkyRow[] AktSverky1) {
            object[] results = this.Invoke("AktSverky", new object[] {
                        Customer,
                        Date1,
                        Date2});
            AktSverky1 = ((AktSverkyRow[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AktSverkyAsync(Customers Customer, System.DateTime Date1, System.DateTime Date2) {
            this.AktSverkyAsync(Customer, Date1, Date2, null);
        }
        
        /// <remarks/>
        public void AktSverkyAsync(Customers Customer, System.DateTime Date1, System.DateTime Date2, object userState) {
            if ((this.AktSverkyOperationCompleted == null)) {
                this.AktSverkyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAktSverkyOperationCompleted);
            }
            this.InvokeAsync("AktSverky", new object[] {
                        Customer,
                        Date1,
                        Date2}, this.AktSverkyOperationCompleted, userState);
        }
        
        private void OnAktSverkyOperationCompleted(object arg) {
            if ((this.AktSverkyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AktSverkyCompleted(this, new AktSverkyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:GetImage", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int GetImage(Customers Customer, string GoodsCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> Index, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] out byte[] Data) {
            object[] results = this.Invoke("GetImage", new object[] {
                        Customer,
                        GoodsCode,
                        Index});
            Data = ((byte[])(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetImageAsync(Customers Customer, string GoodsCode, System.Nullable<int> Index) {
            this.GetImageAsync(Customer, GoodsCode, Index, null);
        }
        
        /// <remarks/>
        public void GetImageAsync(Customers Customer, string GoodsCode, System.Nullable<int> Index, object userState) {
            if ((this.GetImageOperationCompleted == null)) {
                this.GetImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImageOperationCompleted);
            }
            this.InvokeAsync("GetImage", new object[] {
                        Customer,
                        GoodsCode,
                        Index}, this.GetImageOperationCompleted, userState);
        }
        
        private void OnGetImageOperationCompleted(object arg) {
            if ((this.GetImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImageCompleted(this, new GetImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:GetNewsList", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string GetNewsList(Customers Customer, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime Date, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] out News[] News) {
            object[] results = this.Invoke("GetNewsList", new object[] {
                        Customer,
                        Date});
            News = ((News[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewsListAsync(Customers Customer, System.DateTime Date) {
            this.GetNewsListAsync(Customer, Date, null);
        }
        
        /// <remarks/>
        public void GetNewsListAsync(Customers Customer, System.DateTime Date, object userState) {
            if ((this.GetNewsListOperationCompleted == null)) {
                this.GetNewsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewsListOperationCompleted);
            }
            this.InvokeAsync("GetNewsList", new object[] {
                        Customer,
                        Date}, this.GetNewsListOperationCompleted, userState);
        }
        
        private void OnGetNewsListOperationCompleted(object arg) {
            if ((this.GetNewsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewsListCompleted(this, new GetNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:GetCustomerInfo", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string GetCustomerInfo(Customers Customer, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out CustomerInfo CustomerInfo) {
            object[] results = this.Invoke("GetCustomerInfo", new object[] {
                        Customer});
            CustomerInfo = ((CustomerInfo)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerInfoAsync(Customers Customer) {
            this.GetCustomerInfoAsync(Customer, null);
        }
        
        /// <remarks/>
        public void GetCustomerInfoAsync(Customers Customer, object userState) {
            if ((this.GetCustomerInfoOperationCompleted == null)) {
                this.GetCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("GetCustomerInfo", new object[] {
                        Customer}, this.GetCustomerInfoOperationCompleted, userState);
        }
        
        private void OnGetCustomerInfoOperationCompleted(object arg) {
            if ((this.GetCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerInfoCompleted(this, new GetCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:AVDClientRegistration", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string AVDClientRegistration(string RegistrationKey) {
            object[] results = this.Invoke("AVDClientRegistration", new object[] {
                        RegistrationKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AVDClientRegistrationAsync(string RegistrationKey) {
            this.AVDClientRegistrationAsync(RegistrationKey, null);
        }
        
        /// <remarks/>
        public void AVDClientRegistrationAsync(string RegistrationKey, object userState) {
            if ((this.AVDClientRegistrationOperationCompleted == null)) {
                this.AVDClientRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAVDClientRegistrationOperationCompleted);
            }
            this.InvokeAsync("AVDClientRegistration", new object[] {
                        RegistrationKey}, this.AVDClientRegistrationOperationCompleted, userState);
        }
        
        private void OnAVDClientRegistrationOperationCompleted(object arg) {
            if ((this.AVDClientRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AVDClientRegistrationCompleted(this, new AVDClientRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:SendMessage", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string SendMessage(Customers Customer, string Topic, string Message, string Destination) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        Customer,
                        Topic,
                        Message,
                        Destination});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(Customers Customer, string Topic, string Message, string Destination) {
            this.SendMessageAsync(Customer, Topic, Message, Destination, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(Customers Customer, string Topic, string Message, string Destination, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        Customer,
                        Topic,
                        Message,
                        Destination}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:GetAVDClientVersion", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string GetAVDClientVersion() {
            object[] results = this.Invoke("GetAVDClientVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAVDClientVersionAsync() {
            this.GetAVDClientVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetAVDClientVersionAsync(object userState) {
            if ((this.GetAVDClientVersionOperationCompleted == null)) {
                this.GetAVDClientVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAVDClientVersionOperationCompleted);
            }
            this.InvokeAsync("GetAVDClientVersion", new object[0], this.GetAVDClientVersionOperationCompleted, userState);
        }
        
        private void OnGetAVDClientVersionOperationCompleted(object arg) {
            if ((this.GetAVDClientVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAVDClientVersionCompleted(this, new GetAVDClientVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:UpdateAVDClient", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string UpdateAVDClient(Customers Customer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] out byte[] Application) {
            object[] results = this.Invoke("UpdateAVDClient", new object[] {
                        Customer});
            Application = ((byte[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAVDClientAsync(Customers Customer) {
            this.UpdateAVDClientAsync(Customer, null);
        }
        
        /// <remarks/>
        public void UpdateAVDClientAsync(Customers Customer, object userState) {
            if ((this.UpdateAVDClientOperationCompleted == null)) {
                this.UpdateAVDClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAVDClientOperationCompleted);
            }
            this.InvokeAsync("UpdateAVDClient", new object[] {
                        Customer}, this.UpdateAVDClientOperationCompleted, userState);
        }
        
        private void OnUpdateAVDClientOperationCompleted(object arg) {
            if ((this.UpdateAVDClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAVDClientCompleted(this, new UpdateAVDClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webstore.org#WebStore:AVDClientRegistrationIP", RequestNamespace="http://www.webstore.org", ResponseNamespace="http://www.webstore.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string AVDClientRegistrationIP(string RegistrationKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IP) {
            object[] results = this.Invoke("AVDClientRegistrationIP", new object[] {
                        RegistrationKey,
                        IP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AVDClientRegistrationIPAsync(string RegistrationKey, string IP) {
            this.AVDClientRegistrationIPAsync(RegistrationKey, IP, null);
        }
        
        /// <remarks/>
        public void AVDClientRegistrationIPAsync(string RegistrationKey, string IP, object userState) {
            if ((this.AVDClientRegistrationIPOperationCompleted == null)) {
                this.AVDClientRegistrationIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAVDClientRegistrationIPOperationCompleted);
            }
            this.InvokeAsync("AVDClientRegistrationIP", new object[] {
                        RegistrationKey,
                        IP}, this.AVDClientRegistrationIPOperationCompleted, userState);
        }
        
        private void OnAVDClientRegistrationIPOperationCompleted(object arg) {
            if ((this.AVDClientRegistrationIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AVDClientRegistrationIPCompleted(this, new AVDClientRegistrationIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class Customers {
        
        private string loginField;
        
        private string codeField;
        
        private string registrationKeyField;
        
        private string ipField;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationKey {
            get {
                return this.registrationKeyField;
            }
            set {
                this.registrationKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class OrdersDolgRow {
        
        private System.DateTime dateField;
        
        private string numberField;
        
        private System.DateTime payDateField;
        
        private int daysField;
        
        private float summaDolgField;
        
        private float prosrochenoField;
        
        private float todayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PayDate {
            get {
                return this.payDateField;
            }
            set {
                this.payDateField = value;
            }
        }
        
        /// <remarks/>
        public int Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        public float SummaDolg {
            get {
                return this.summaDolgField;
            }
            set {
                this.summaDolgField = value;
            }
        }
        
        /// <remarks/>
        public float Prosrocheno {
            get {
                return this.prosrochenoField;
            }
            set {
                this.prosrochenoField = value;
            }
        }
        
        /// <remarks/>
        public float Today {
            get {
                return this.todayField;
            }
            set {
                this.todayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class CustomerInfo {
        
        private string managerNameField;
        
        private string managerPhoneField;
        
        private string managerEmailField;
        
        private string managerSkipeField;
        
        private string managerICQField;
        
        private float summaCreditField;
        
        private string currencyField;
        
        private float dayCreditField;
        
        private string fIOField;
        
        private string deliveryInfoField;
        
        private float summaDolgField;
        
        private OrdersDolgRow[] ordersDolgField;
        
        private float eURField;
        
        private float uSDField;
        
        /// <remarks/>
        public string ManagerName {
            get {
                return this.managerNameField;
            }
            set {
                this.managerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerPhone {
            get {
                return this.managerPhoneField;
            }
            set {
                this.managerPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerEmail {
            get {
                return this.managerEmailField;
            }
            set {
                this.managerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerSkipe {
            get {
                return this.managerSkipeField;
            }
            set {
                this.managerSkipeField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerICQ {
            get {
                return this.managerICQField;
            }
            set {
                this.managerICQField = value;
            }
        }
        
        /// <remarks/>
        public float SummaCredit {
            get {
                return this.summaCreditField;
            }
            set {
                this.summaCreditField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public float DayCredit {
            get {
                return this.dayCreditField;
            }
            set {
                this.dayCreditField = value;
            }
        }
        
        /// <remarks/>
        public string FIO {
            get {
                return this.fIOField;
            }
            set {
                this.fIOField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryInfo {
            get {
                return this.deliveryInfoField;
            }
            set {
                this.deliveryInfoField = value;
            }
        }
        
        /// <remarks/>
        public float SummaDolg {
            get {
                return this.summaDolgField;
            }
            set {
                this.summaDolgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrdersDolg")]
        public OrdersDolgRow[] OrdersDolg {
            get {
                return this.ordersDolgField;
            }
            set {
                this.ordersDolgField = value;
            }
        }
        
        /// <remarks/>
        public float EUR {
            get {
                return this.eURField;
            }
            set {
                this.eURField = value;
            }
        }
        
        /// <remarks/>
        public float USD {
            get {
                return this.uSDField;
            }
            set {
                this.uSDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class News {
        
        private string idField;
        
        private string dateField;
        
        private string infoField;
        
        private string htmlField;
        
        private byte[] image001Field;
        
        private byte[] image002Field;
        
        private byte[] image003Field;
        
        private byte[] image004Field;
        
        private byte[] image005Field;
        
        private byte[] image006Field;
        
        private byte[] image007Field;
        
        private byte[] image008Field;
        
        private byte[] image009Field;
        
        private byte[] image010Field;
        
        private int imgsCountField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public string html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image001 {
            get {
                return this.image001Field;
            }
            set {
                this.image001Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image002 {
            get {
                return this.image002Field;
            }
            set {
                this.image002Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image003 {
            get {
                return this.image003Field;
            }
            set {
                this.image003Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image004 {
            get {
                return this.image004Field;
            }
            set {
                this.image004Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image005 {
            get {
                return this.image005Field;
            }
            set {
                this.image005Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image006 {
            get {
                return this.image006Field;
            }
            set {
                this.image006Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image007 {
            get {
                return this.image007Field;
            }
            set {
                this.image007Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image008 {
            get {
                return this.image008Field;
            }
            set {
                this.image008Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image009 {
            get {
                return this.image009Field;
            }
            set {
                this.image009Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image010 {
            get {
                return this.image010Field;
            }
            set {
                this.image010Field = value;
            }
        }
        
        /// <remarks/>
        public int ImgsCount {
            get {
                return this.imgsCountField;
            }
            set {
                this.imgsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class AktSverkyRow {
        
        private string dateField;
        
        private string numberField;
        
        private string documentField;
        
        private float paymentField;
        
        private float shippingField;
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public float Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public float Shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class Invoice {
        
        private string numberField;
        
        private string dateField;
        
        private float totalField;
        
        private string deliveryInfoField;
        
        private string statusField;
        
        private string deliveryDateField;
        
        private string invoiceIDField;
        
        private string currencyField;
        
        private Table[] tableField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public float Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryInfo {
            get {
                return this.deliveryInfoField;
            }
            set {
                this.deliveryInfoField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Table")]
        public Table[] Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class Table {
        
        private int numField;
        
        private string codeField;
        
        private float priceField;
        
        private float quantityField;
        
        private float totalField;
        
        /// <remarks/>
        public int Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public float Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public float Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webstore.org")]
    public partial class Order {
        
        private string orderNumberField;
        
        private Customers customerField;
        
        private Table[] tableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        public Customers Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Table")]
        public Table[] Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FormOrderCompletedEventHandler(object sender, FormOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateDatabaseCompletedEventHandler(object sender, UpdateDatabaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public byte[] Data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInvoiceListCompletedEventHandler(object sender, GetInvoiceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Invoice[] InvoiceList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Invoice[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AktSverkyCompletedEventHandler(object sender, AktSverkyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AktSverkyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AktSverkyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public AktSverkyRow[] AktSverky1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AktSverkyRow[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetImageCompletedEventHandler(object sender, GetImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public byte[] Data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetNewsListCompletedEventHandler(object sender, GetNewsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public News[] News {
            get {
                this.RaiseExceptionIfNecessary();
                return ((News[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCustomerInfoCompletedEventHandler(object sender, GetCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public CustomerInfo CustomerInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerInfo)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AVDClientRegistrationCompletedEventHandler(object sender, AVDClientRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AVDClientRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AVDClientRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAVDClientVersionCompletedEventHandler(object sender, GetAVDClientVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAVDClientVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAVDClientVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateAVDClientCompletedEventHandler(object sender, UpdateAVDClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAVDClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAVDClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public byte[] Application {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AVDClientRegistrationIPCompletedEventHandler(object sender, AVDClientRegistrationIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AVDClientRegistrationIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AVDClientRegistrationIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591