//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVDClient.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
        string GetUserName()
        {
            return System.Environment.UserName;
        }

        string GetComputerName()
        {
            return System.Environment.MachineName;
        }

        string VolumeSerialNumber()
        {
            try
            {
                string drive = System.Environment.GetFolderPath(System.Environment.SpecialFolder.System).Substring(0, 1);
                System.Management.ManagementObject disk = new System.Management.ManagementObject("win32_logicaldisk.deviceid=\"" + drive + ":\"");
                disk.Get();
                return (disk["VolumeSerialNumber"].ToString());

            }
            catch (System.Exception)
            {
                return "";
            }
        }

        string GetHashString(string s)
        {
            //переводим строку в байт-массим  
            byte[] bytes = System.Text.Encoding.Unicode.GetBytes(s);

            //создаем объект для получения средст шифрования  
            System.Security.Cryptography.MD5CryptoServiceProvider CSP =
                new System.Security.Cryptography.MD5CryptoServiceProvider();

            //вычисляем хеш-представление в байтах  
            byte[] byteHash = CSP.ComputeHash(bytes);

            string hash = string.Empty;

            //формируем одну цельную строку из массива  
            foreach (byte b in byteHash)
                hash += string.Format("{0:x2}", b);

            return hash;
        }


        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\dt.sdf")]
        public string MyDatabaseConnectionString
        {
            get
            {
                return ((string)(this["MyDatabaseConnectionString"] + ";Password=" + GetHashString(GetComputerName() + VolumeSerialNumber())));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avdtrade.re2is.info/WebZakaz/ws/WebStore")]
        public string WindowsFormsApplication1_WebStore_WebStore
        {
            get
            {
                return ((string)(this["WindowsFormsApplication1_WebStore_WebStore"]));
            }
        }
    }
}